# Generated by Django 5.2.4 on 2025-07-28 08:24

from django.db import migrations
from django.db.models import F


def indicate_price_product(apps, schema_editor):
    OrderProducts = apps.get_model('foodcartapp', 'OrderProducts')
    db_alias = schema_editor.connection.alias

    OrderProducts.objects.using(db_alias).update(price=F('product__price'))


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_orderproducts_price_restaurantmenuitem_price'),
    ]

    operations = [
        migrations.RunPython(indicate_price_product),
    ]
