# Generated by Django 5.2.6 on 2025-09-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_payment_method_alter_orderproducts_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderProduct',
        ),
    ]
