# Generated by Django 5.2.6 on 2025-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронный'), ('K', 'Картой')], db_index=True, max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
