# Generated by Django 5.2.6 on 2025-09-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_orderproducts_order_alter_orderproducts_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='foodcartapp.product', verbose_name='Продукты для заказа'),
        ),
    ]
