# Generated by Django 5.2.6 on 2025-09-05 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_orderproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Количество'),
        ),
    ]
