# Generated by Django 5.2.6 on 2025-09-05 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_orderproducts_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
