# Generated by Django 5.2.6 on 2025-10-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_orderproduct_price_alter_orderproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('N', 'Не выбран'), ('C', 'Наличными'), ('E', 'Электронный'), ('K', 'Картой')], db_index=True, default='N', max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
