# Generated by Django 5.2.6 on 2025-09-05 16:53

from django.db import migrations


def combine_names(apps, schema_editor):
    Person = apps.get_model('foodcartapp', 'Order')
    for person in Person.objects.all():
        person.name = f"{person.first_name} {person.last_name}"
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_orderproducts_price'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
