# Generated by Django 5.2.6 on 2025-09-05 16:53

from django.db import migrations


def replace_null_with_empty_string(apps, schema_editor):
    ModelName = apps.get_model('foodcartapp', 'Order')
    db_alias = schema_editor.connection.alias

    ModelName.objects.using(db_alias).filter(firstname__isnull=True).update(firstname='')
    ModelName.objects.using(db_alias).filter(lastname__isnull=True).update(lastname='')


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_orderproducts_price'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_string),
    ]
