# Generated by Django 5.2.6 on 2025-10-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenuitem',
            name='price',
        ),
    ]
