# Generated by Django 5.2.6 on 2025-09-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_orderproduct_delete_orderproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenuitem',
            name='price',
        ),
    ]
