# Generated by Django 5.2.6 on 2025-10-05 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_remove_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена'),
        ),
    ]
