# Generated by Django 5.2.6 on 2025-09-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfostore', '0003_rename_geocodecache_geocodingaddresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.CharField(max_length=255, unique=True, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
        ),
        migrations.DeleteModel(
            name='GeocodingAddresses',
        ),
    ]
